site_name: Ioannis Papaspyridis
site_description: Personal site built with Material for MkDocs
site_author: Ioannis Papaspyridis
site_url: https://yiakonale.github.io/
repo_url: https://github.com/yiakonale
repo_name: github.com/yiakonale
  
theme:
  name: material
  palette:
    - scheme: slate        # Dark mode (default)
      primary: custom
      accent: custom
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode
    - scheme: default      # Light mode
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    # --- Navigation behavior ---
    - navigation.top
    - navigation.tabs              # Show top-level items as tabs on top
#    - navigation.tabs.sticky       # Keep tabs visible when scrolling
#    - navigation.sections          # Show child pages grouped under section tabs
    - toc.integrate                # Move page index (table of contents) into main content column
#    - header.autohide              # (optional) hides header on scroll down, reappears on scroll up
    - content.code.copy            # Add copy buttons on code blocks
    - content.code.annotate        # Enable code annotations
    - search.highlight
    - search.share

extra_css:
  - styles/custom-colors.css

nav:
  - About: index.md
  - Projects: projects.md
#  - About: about.md
#  - Test: projects/pcb.md #COMMENT OUT BEFORE PUSHING
  - Blog:
      - Hello World: blog/1_first-post.md
      - About Me: blog/2_about-me.md

plugins:
  - search
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - codehilite
  - toc
#      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.emoji
  - pymdownx.tabbed

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yiakonale
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/ipapaspyridis
      
copyright: Copyright &copy; 2025 Ioannis Papaspyridis